spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      username: 
      password: 
      database: dummy
     
---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost2
      port: 27017
      username: 
      password: 
      database: dummy
     
     